# Generated by Django 4.0.5 on 2022-10-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projectss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technologies', models.TextField()),
                ('images', models.ImageField(upload_to='projects/images')),
                ('videos', models.FileField(upload_to='projects/videos')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
