# Generated by Django 4.0.5 on 2022-10-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectss',
            name='images',
        ),
        migrations.AddField(
            model_name='projectss',
            name='images_one',
            field=models.ImageField(default='', upload_to='projects/images_one'),
        ),
        migrations.AddField(
            model_name='projectss',
            name='images_three',
            field=models.ImageField(default='', upload_to='projects/images_three'),
        ),
        migrations.AddField(
            model_name='projectss',
            name='images_two',
            field=models.ImageField(default='', upload_to='projects/images_two'),
        ),
    ]
