# Generated by Django 4.0.5 on 2022-10-10 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StackApp', '0002_remove_projectss_images_projectss_images_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectss',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
