# Generated by Django 4.0.5 on 2022-10-10 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackApp', '0003_projectss_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectss',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
