# Generated by Django 4.0.5 on 2022-10-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackApp', '0004_alter_projectss_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thisapp_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Repeat_pass', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Profession', models.CharField(max_length=100)),
            ],
        ),
    ]
