# Generated by Django 4.0.5 on 2022-10-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StackApp', '0005_thisapp_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thisapp_Users',
        ),
    ]
